# site settings
title: jimbowery
subtitle: ---
email: jim@jimbowery.com
description: when life gives you oranges
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: jim@jimbowery.com
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/jimbowery
  GitLab:
  Google-Plus: 
  Instagram: https://https://www.instagram.com/jimbowery/
  LinkedIn: https://www.linkedin.com/in/jim-bowery-a9343625/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
